-- MySQL Script generated by MySQL Workbench
-- Wed Apr 26 18:54:38 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tudus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tudus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tudus` DEFAULT CHARACTER SET utf8mb4 ;
USE `tudus` ;


-- -----------------------------------------------------
-- Table `tudus`.`timezones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tudus`.`timezones` (
  `utc_code` VARCHAR(20) NOT NULL,
  `utc_name` VARCHAR(45) NULL,
  `utc_ko_name` VARCHAR(45) NULL,
  `utc_en_name` VARCHAR(45) NULL,
  `gmt_time` INT UNSIGNED NULL,
  PRIMARY KEY (`utc_code`),
  UNIQUE INDEX `utc_code_UNIQUE` (`utc_code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tudus`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tudus`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `pwd` VARCHAR(255) NOT NULL,
  `user_name` VARCHAR(100) NOT NULL,
  `first_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NULL,
  `nickname` VARCHAR(100) NULL,
  `gender` TINYINT NULL,
  `birth_date` DATETIME NULL,
  `site_url` VARCHAR(255) NULL,
  `lang_type` VARCHAR(45) NULL,
  `utc_type` VARCHAR(45) NULL,
  `is_active` TINYINT NULL DEFAULT 0,
  `is_blocked` TINYINT NULL DEFAULT 0,
  `last_signin_ip` VARCHAR(128) NULL,
  `last_signin_date` DATETIME NULL,
  `create_date` DATETIME NULL,
  `update_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idusers_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tudus`.`user_access`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tudus`.`user_access` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `token` VARCHAR(200) NOT NULL,
  `ip` VARCHAR(128) NULL,
  `create_date` DATETIME NULL,
  `device_id` VARCHAR(45) NULL,
  INDEX `fk_user_access_users1_idx` (`user_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tudus`.`issues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tudus`.`issues` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `title` VARCHAR(255) NULL,
  `content` TEXT NULL,
  `issue_status` TINYINT NULL,
  `issue_type` TINYINT NULL,
  `create_date` DATETIME NULL,
  `last_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `content_id_UNIQUE` (`id` ASC),
  INDEX `fk_contents_users_idx` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tudus`.`links`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tudus`.`links` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(255) NULL,
  `title` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `target` VARCHAR(25) NULL,
  `description` VARCHAR(255) NULL,
  `rss_url` VARCHAR(255) NULL,
  `create_date` DATETIME NULL,
  `update_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `link_id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tudus`.`issue_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tudus`.`issue_comments` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `issue_id` INT NOT NULL,
  `content` TEXT NULL,
  `ip` VARCHAR(128) NULL,
  `create_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_users1_idx` (`user_id` ASC),
  INDEX `fk_comments_contents1_idx` (`issue_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tudus`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tudus`.`tasks` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `parent_task_id` INT NOT NULL,
  `target_user_id` INT NOT NULL,
  `reg_user_id` INT NOT NULL,
  `issue_id` INT NOT NULL,
  `title` VARCHAR(255) NULL,
  `status` TINYINT NULL,
  `priority` TINYINT NULL,
  `start_date` DATETIME NULL,
  `end_date` DATETIME NULL,
  `create_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `task_id_UNIQUE` (`id` ASC),
  INDEX `fk_tasks_tasks1_idx` (`parent_task_id` ASC),
  INDEX `fk_tasks_users1_idx` (`target_user_id` ASC),
  INDEX `fk_tasks_users2_idx` (`reg_user_id` ASC),
  INDEX `fk_tasks_issues1_idx` (`issue_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tudus`.`issues_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tudus`.`issues_history` (
  `issue_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NULL,
  `issue_status` TINYINT NULL,
  `issue_type` TINYINT NULL,
  `create_date` DATETIME NULL,
  `update_date` DATETIME NULL,
  PRIMARY KEY (`issue_id`),
  UNIQUE INDEX `content_id_UNIQUE` (`issue_id` ASC),
  INDEX `fk_contents_users_idx` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tudus`.`issue_changes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tudus`.`issue_changes` (
  `issue_id` INT NOT NULL,
  `issue_history_id` INT NOT NULL,
  INDEX `fk_issue_changes_issues1_idx` (`issue_id` ASC),
  INDEX `fk_issue_changes_issues_history1_idx` (`issue_history_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tudus`.`task_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tudus`.`task_history` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `parent_task_id` INT NOT NULL,
  `target_user_id` INT NOT NULL,
  `reg_user_id` INT NOT NULL,
  `issue_id` INT NULL,
  `title` VARCHAR(255) NULL,
  `status` TINYINT NULL,
  `priority` TINYINT NULL,
  `start_date` DATETIME NULL,
  `end_date` DATETIME NULL,
  `create_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `task_id_UNIQUE` (`id` ASC),
  INDEX `fk_tasks_tasks1_idx` (`parent_task_id` ASC),
  INDEX `fk_tasks_users1_idx` (`target_user_id` ASC),
  INDEX `fk_tasks_users2_idx` (`reg_user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tudus`.`task_changes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tudus`.`task_changes` (
  `task_id` INT NOT NULL,
  `task_history_id` INT NOT NULL,
  INDEX `fk_task_changes_tasks1_idx` (`task_id` ASC),
  INDEX `fk_task_changes_task_history1_idx` (`task_history_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tudus`.`signin_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tudus`.`signin_logs` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `token` VARCHAR(255) NULL,
  `ip` VARCHAR(128) NULL,
  `signin_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_signin_history_users1_idx` (`user_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tudus`.`schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tudus`.`schedules` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NULL,
  `location` VARCHAR(255) NULL,
  `start_date` DATETIME NULL,
  `end_date` DATETIME NULL,
  `create_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_schedules_users1_idx` (`user_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tudus`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tudus`.`groups` (
  `group_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `photo_url` VARCHAR(255) NULL,
  `create_date` DATETIME NULL,
  `update_date` DATETIME NULL,
  PRIMARY KEY (`group_id`),
  UNIQUE INDEX `group_id_UNIQUE` (`group_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tudus`.`group_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tudus`.`group_users` (
  `group_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  INDEX `fk_group_users_groups1_idx` (`group_id` ASC),
  INDEX `fk_group_users_users1_idx` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tudus`.`relationship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tudus`.`relationship` (
  `action_user_id` INT NOT NULL COMMENT '행위자\n',
  `user_one_id` INT NOT NULL COMMENT 'source\n',
  `user_two_id` INT NOT NULL COMMENT 'target\n',
  `status` TINYINT NULL COMMENT '0: 대기\n1: 수락\n2: 거부\n3: blocked',
  INDEX `fk_relationship_users1_idx` (`action_user_id` ASC),
  INDEX `fk_relationship_users2_idx` (`user_one_id` ASC),
  INDEX `fk_relationship_users3_idx` (`user_two_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tudus`.`decisions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tudus`.`decisions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `confirm_user_id` INT NOT NULL,
  `title` VARCHAR(255) NULL,
  `content` TEXT NULL,
  `confirm_type` TINYINT NULL,
  `confirm_status` TINYINT NULL,
  `create_date` DATETIME NULL,
  `update_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_decisions_users1_idx` (`user_id` ASC),
  INDEX `fk_decisions_users2_idx` (`confirm_user_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tudus`.`task_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tudus`.`task_comments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `task_id` INT NOT NULL,
  `content` TEXT NULL,
  `ip` VARCHAR(128) NULL,
  `create_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_users1_idx` (`user_id` ASC),
  INDEX `fk_task_comments_tasks1_idx` (`task_id` ASC),
  UNIQUE INDEX `comment_id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tudus`.`schedule_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tudus`.`schedule_comments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `schedule_id` INT NOT NULL,
  `content` TEXT NULL,
  `ip` VARCHAR(128) NULL,
  `create_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_users1_idx` (`user_id` ASC),
  INDEX `fk_issue_comments_copy1_schedules1_idx` (`schedule_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tudus`.`channels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tudus`.`channels` (
  `channel_id` INT NOT NULL,
  `create_user_id` INT NULL,
  `name` VARCHAR(128) NULL,
  `description` VARCHAR(255) NULL,
  `status` TINYINT NULL,
  `invite_code` VARCHAR(128) NULL,
  `create_date` DATETIME NULL,
  PRIMARY KEY (`channel_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tudus`.`channel_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tudus`.`channel_users` (
  `channel_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `user_level` TINYINT NULL,
  `user_status` TINYINT NULL,
  `join_date` DATETIME NULL,
  INDEX `fk_channel_users_channels1_idx` (`channel_id` ASC),
  INDEX `fk_channel_users_users1_idx` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tudus`.`decision_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tudus`.`decision_comments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `decision_id` INT NOT NULL,
  `content` TEXT NULL,
  `ip` VARCHAR(128) NULL,
  `create_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_users1_idx` (`user_id` ASC),
  INDEX `fk_schedule_comments_copy1_decisions1_idx` (`decision_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tudus`.`user_updates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tudus`.`user_updates` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `update` VARCHAR(45) NULL,
  `ip` VARCHAR(128) NULL,
  `create_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_updates_users1_idx` (`user_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
